name: test_mobie_project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mobie_utils
  - magicgui
  - pyqt
  - pip
  - pip:
    - bioio
    - bioio-ome-zarr
    - bioio-ome-tiff
    - bioio_tifffile
    - pillow